\newlabel{fig:sub1}
\newlabel{fig:sub1}
\newlabel{fig:sub2}
\newlabel{fig:sub2}
\newlabel{fig:sub2}
\newlabel{fig:test}
\newlabel{fig:test}
\newlabel{sub@fig:sub1}
\newlabel{sub@fig:sub1}
\newlabel{sub@fig:sub2}
\newlabel{sub@fig:sub2}
